# Generated by Django 4.2.7 on 2023-11-28 13:56

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('note', djrichtextfield.models.RichTextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
