# Generated by Django 4.2.7 on 2023-11-28 16:09

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=djrichtextfield.models.RichTextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
